// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewLink struct {
	URL string `json:"url"`
}

type ShortLink struct {
	ID       string      `json:"id"`
	Endpoint string      `json:"endpoint"`
	Target   *TargetLink `json:"target"`
}

type TargetLink struct {
	ID        string     `json:"id"`
	URL       string     `json:"url"`
	Shortened *ShortLink `json:"shortened"`
}
