PORT: "8080"
Postgres:
  Host: localhost:5678
  User: admin
  Password: admin
  Name: urls
Redis:
  Host: localhost:6379  # host:port combination; required
  Password: replace me  # redis connection password; optional; default is none
  Db: 0                 # redis index (https://redis.io/commands/select); optional; default is 0
  Max_Retries: 3         # maximum number of retries for a failed redis command
  Read_Timeout: 3s       # timeout for read operations; default is 3s. This is a golang time.ParseDuration string
  Write_Timeout: 3s      # timeout for write operations; default is 3s. This is a golang time.ParseDuration string
  Session_DB: 1          # redis session store index (https://redis.io/commands/select); optional; default is 1
  Shared_Key: replace me # redis session store shared key; optional; default is "secret"